#ifndef GAME_H
#define GAME_H
#include <vector>
#include <SDL.h>
#include <SDL_ttf.h>
#include "Bird.h"
#include "Pipe.h"
#include "Bomb.h"
#include "Rocket.h"
#include "AudioManager.h"
#include "Screen.h"
#include "Constants.h"

class Game
{
private:
    SDL_Renderer* renderer;
    SDL_Texture* backgroundTexture;
    SDL_Texture* upperPipeTexture;
    SDL_Texture* lowerPipeTexture;
    SDL_Texture* bombTexture;
    SDL_Texture* rocketTexture;
    Bird* bird;
    std::vector<Pipe*> pipes;
    std::vector<Bomb*> bombs;
    std::vector<Rocket*> rockets;
    AudioManager* audioManager;
    bool running;
    bool gameStarted;
    bool isExploding;
    bool isPaused;
    bool isCountingDown;
    int countdownTimer;
    int countdownNumber;
    int score;
    int frameCount;
    int rocketFrameCount;
    int explodeTimer;
    TTF_Font* font;
    SDL_Texture* scoreTexture;
    SDL_Rect scoreRect;
    SDL_Texture* explosionTexture;
    SDL_Rect explosionRect;
    SDL_Rect explosionSrcRect;
    int explosionFrame;
    int explosionFrameCount;
    int pipeSpeed;
    int bombSpeed;
    int bombSpawnRate;
    int rocketVerticalSpeed;
    float gravity;
    float jumpForce;
    SDL_Texture* startButtonTexture;
    SDL_Rect startButtonRect;
    SDL_Texture* flappyBirdTitleTexture;
    SDL_Rect flappyBirdTitleRect;
    bool levelSelection;
    SDL_Texture* panelTexture;
    SDL_Rect levelPanelRect;
    SDL_Texture* level1ButtonTexture;
    SDL_Rect level1ButtonRect;
    SDL_Texture* level2ButtonTexture;
    SDL_Rect level2ButtonRect;
    SDL_Texture* levelAsianButtonTexture;
    SDL_Rect levelAsianButtonRect;
    int currentLevel;
    int highScores[3];
    SDL_Texture* highScoreTexture;
    SDL_Rect highScoreRect;
    SDL_Texture* currentScoreTexture;
    SDL_Rect currentScoreRect;
    SDL_Texture* replayButtonTexture;
    SDL_Rect replayButtonRect;
    SDL_Rect gameOverPanelRect;
    SDL_Texture* exitButtonTexture;
    SDL_Rect exitButtonRect;
    int shakeTimer;
    int shakeIntensity;
    int shakeOffsetX;
    int shakeOffsetY;
    void updateScoreTexture();
    void spawnPipe();
    void spawnBomb();
    void spawnRocket();
    void checkCollisions();
    void updateScore();
    void updateHighScoreTexture();
    void updateCurrentScoreTexture();
public:
    Game(SDL_Renderer* renderer);
    ~Game();
    void run();
    void handleEvents();
    void update();
    void render();
    int getPipeSpeed() const { return pipeSpeed; }
    int getBombSpeed() const { return bombSpeed; }
};
#endif
